version: "3"
services:
  app:
    image: docker.fiveone.com:5000/sendgrid-tracking:development
    volumes:
      - ./src:/html
    env_file:
      - docker/db/env
    environment:
      - APP_ENV
      - APP_DEBUG
      - APP_KEY
    depends_on:
      - web
      - db
      - mail
  web:
    image: docker.fiveone.com:5000/sendgrid-tracking-web:latest
    volumes:
      - ./src:/html
    ports:
      - "80:80"
  db:
    image: docker.fiveone.com:5000/sendgrid-tracking-db:latest
    env_file:
      - docker/db/env
  adminer:
    build: ./docker/adminer
    env_file:
      - docker/db/env
    depends_on:
      - db
    ports:
      - "8080:8080"
  mail:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
